spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: eureka-provider
          uri: lb://EUREKA-PROVIDER
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://songyuankun.com:8761/eureka/