server:
  port: 8000
  servlet:
    context-path: /
spring:
  application:
    name: api-geteway
eureka:
  client:
    serviceUrl:
      defaultZone: http://songyuankun.com:8761/eureka/
  instance:
    hostname: songyuankun.com
zuul:
  routes:
    eureka-provider: book/**
