server:
  port: 5000
spring:
  application:
    name: api-geteway
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka-server/eureka/
zuul:
  routes:
    spring-boot-demo:
      path: /api/**
