server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: eureka-provider
  #  security:
  #    user:
  #      name: songyuankun
  #      password: songyuankun
  datasource:
    url: jdbc:mysql://60.205.221.172/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kun3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  output:
    ansi:
      enabled: detect
  redis:
    database: 0
    host: 60.205.221.172
    port: 6379
    password: 123456
  cache:
    type: redis
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.songyuankun.top/eureka/,http://eureka2.songyuankun.top/eureka/
  instance:
    hostname: songyuankun.top
management:
  endpoints:
    web:
      exposure:
        include: '*'

