server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: eureka-provider
  security:
    user:
      name: songyuankun
      password: songyuankun

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.songyuankun.top/eureka/,http://eureka2.songyuankun.top/eureka/
  instance:
    hostname: songyuankun.top
management:
  endpoints:
    web:
      exposure:
        include: *
