server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://songyuankun:songyuankun@cluster0-xrqrk.mongodb.net/demo?retryWrites=true
  datasource:
    url: jdbc:mysql://60.205.221.172/mysqltest?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kun3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    redis:
      database: 0
      host: 60.205.221.172
      port: 7000
      password: 123456
    mode: HTML5
my:
  version: 2019年5月5日17:33:19