server:
  port: 8761
  servlet:
    context-path: /eureka-server
eureka:
  instance:
    hostname: songyuankun.top
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka-server/eureka/

spring:
  application:
    name: eurka-server

