server:
  port: 8761
  servlet:
    context-path: /
eureka:
  instance:
    hostname: songyuankun.com
  client:
    serviceUrl:
      defaultZone: http://songyuankun.com:8762/eureka/

spring:
  application:
    name: eurka-server

