server:
  port: 8761
  servlet:
    context-path: /
eureka:
  instance:
    hostname: songyuankun.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

