server:
  port: 8762
  servlet:
    context-path: /
eureka:
  instance:
    hostname: songyuankun.com
  client:
    serviceUrl:
      defaultZone: http://songyuankun.com:8761/eureka/

spring:
  application:
    name: eurka-server

