server:
  port: 9000

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.songyuankun.top/eureka/,http://eureka2.songyuankun.top/eureka/

feign:
  hystrix:
    enabled: true