server:
  port: 9000

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://songyuankun.com:8761/eureka/,http://songyuankun.com:8762/eureka/

feign:
  hystrix:
    enabled: true