server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SongYuanKun/spring-cloud-demo
          search-paths: /*/*/*,/*
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: songyuankun
    password: songyuankun
    virtual-host: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.songyuankun.top/eureka/,http://eureka2.songyuankun.top/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh